import type {
  ScheduleItem,
  Task,
  TimelineEvent,
  WorkReport,
} from "./ops-types";

/*
 * 데모 기준 시각: 2026-07-28(화) 10:40
 *
 * 첫 화면 KPI가 아래 값으로 떨어지도록 구성했다.
 *   오늘 예정 업무 12 · 미확인 3 · 기한 초과 2 · 결과보고 대기 4 · 일정 충돌 1
 */

export const TASKS: Task[] = [
  {
    id: "t1",
    title: "서천 장항산단 현장 통신상태 점검",
    projectId: "p2",
    content:
      "B동 통신 단자함 상태를 확인하고 케이블 입고 전에 배선 경로를 다시 점검해 주세요. 확인 후 사진 함께 올려 주세요.",
    assignerId: "u2",
    assigneeId: "u4",
    watcherIds: ["u2"],
    createdAt: "2026-07-27T16:40",
    startDate: "2026-07-28",
    dueAt: "2026-07-28T12:00",
    priority: "긴급",
    needsReport: true,
    needsPhoto: true,
    location: "충남 서천 장항산단 A공장",
    status: "지시됨",
    progress: 0,
    lastUpdateAt: "2026-07-27T16:40",
  },
  {
    id: "t2",
    title: "군산 CCTV 위치 변경 확인",
    projectId: "p4",
    content:
      "발주처가 요청한 CCTV 위치 2개소 변경 지점을 현장에서 확인하고, 추가 4대 설치 위치까지 표시해 주세요.",
    assignerId: "u2",
    assigneeId: "u5",
    watcherIds: ["u2", "u4"],
    createdAt: "2026-07-26T09:00",
    startDate: "2026-07-26",
    dueAt: "2026-07-27T17:00",
    priority: "긴급",
    needsReport: true,
    needsPhoto: true,
    location: "전북 군산 국가산단",
    status: "진행 중",
    acknowledgedAt: "2026-07-26T09:20",
    ackResponse: "확인했습니다",
    progress: 60,
    lastUpdateAt: "2026-07-27T13:40",
  },
  {
    id: "t3",
    title: "보령 공공시설 준공사진 제출",
    projectId: "p6",
    content:
      "준공서류 중 공사사진만 남았습니다. 장비실과 민원실 설치 상태 사진 4장을 촬영해 올려 주세요.",
    assignerId: "u2",
    assigneeId: "u4",
    watcherIds: ["u3"],
    createdAt: "2026-07-27T09:00",
    startDate: "2026-07-27",
    dueAt: "2026-07-28T18:00",
    priority: "긴급",
    needsReport: true,
    needsPhoto: true,
    location: "충남 보령시 공공시설",
    status: "확인함",
    acknowledgedAt: "2026-07-27T09:30",
    ackResponse: "확인했습니다",
    progress: 0,
    lastUpdateAt: "2026-07-27T09:30",
  },
  {
    id: "t4",
    title: "홍성 내포신도시 네트워크 속도 측정",
    projectId: "p3",
    content: "층별 무선 AP 속도를 측정하고 음영 구간이 있으면 위치를 기록해 주세요.",
    assignerId: "u4",
    assigneeId: "u5",
    watcherIds: ["u2"],
    createdAt: "2026-07-28T08:00",
    startDate: "2026-07-28",
    dueAt: "2026-07-28T17:00",
    priority: "보통",
    needsReport: true,
    needsPhoto: false,
    location: "충남 홍성 내포신도시 H금융타워",
    status: "진행 중",
    acknowledgedAt: "2026-07-28T08:20",
    ackResponse: "확인했습니다",
    progress: 40,
    lastUpdateAt: "2026-07-28T09:10",
  },
  {
    id: "t5",
    title: "서천 자재 입고 확인 (TFR-CV 케이블)",
    projectId: "p2",
    content: "대체 거래처에서 오는 케이블 수량과 규격을 확인하고 입고 사진을 남겨 주세요.",
    assignerId: "u2",
    assigneeId: "u6",
    watcherIds: ["u4"],
    createdAt: "2026-07-28T08:30",
    startDate: "2026-07-28",
    dueAt: "2026-07-28T15:00",
    priority: "보통",
    needsReport: true,
    needsPhoto: true,
    location: "충남 서천 장항산단",
    status: "확인함",
    acknowledgedAt: "2026-07-28T08:45",
    ackResponse: "확인했습니다",
    progress: 0,
    lastUpdateAt: "2026-07-28T08:45",
  },
  {
    id: "t6",
    title: "보령시청 준공검수 일정 재확인",
    projectId: "p6",
    content: "담당 주무관과 통화해 검수 일정과 필요한 서류를 다시 확인해 주세요.",
    assignerId: "u2",
    assigneeId: "u3",
    watcherIds: [],
    createdAt: "2026-07-28T09:00",
    startDate: "2026-07-28",
    dueAt: "2026-07-28T16:00",
    priority: "보통",
    needsReport: false,
    needsPhoto: false,
    location: "사무실",
    status: "진행 중",
    acknowledgedAt: "2026-07-28T09:05",
    ackResponse: "확인했습니다",
    progress: 50,
    lastUpdateAt: "2026-07-28T09:40",
  },
  {
    id: "t7",
    title: "서산 한우정식당 견적 수정본 발송",
    content: "CCTV 수량을 4대로 조정한 수정 견적서를 만들어 발송해 주세요.",
    assignerId: "u2",
    assigneeId: "u3",
    watcherIds: [],
    createdAt: "2026-07-24T10:00",
    startDate: "2026-07-24",
    dueAt: "2026-07-27T18:00",
    priority: "보통",
    needsReport: false,
    needsPhoto: false,
    location: "사무실",
    status: "진행 중",
    acknowledgedAt: "2026-07-24T10:30",
    ackResponse: "확인했습니다",
    progress: 70,
    lastUpdateAt: "2026-07-27T11:20",
  },
  {
    id: "t8",
    title: "익산 물류창고 출입통제 장비 사양 정리",
    projectId: "p5",
    content: "출입구 3개소에 들어갈 인식기와 전기정 사양을 정리해 주세요.",
    assignerId: "u2",
    assigneeId: "u6",
    watcherIds: ["u4"],
    createdAt: "2026-07-28T07:50",
    startDate: "2026-07-28",
    dueAt: "2026-07-29T12:00",
    priority: "보통",
    needsReport: false,
    needsPhoto: false,
    location: "전북 익산 제2산단",
    status: "지시됨",
    openedAt: "2026-07-28T08:10",
    progress: 0,
    lastUpdateAt: "2026-07-28T07:50",
  },
  {
    id: "t9",
    title: "대천동 3층 배선 현장일보 제출",
    projectId: "p1",
    content: "오늘 작업 인원과 진행 구간을 정리해 현장일보로 올려 주세요.",
    assignerId: "u4",
    assigneeId: "u5",
    watcherIds: ["u2"],
    createdAt: "2026-07-28T07:30",
    startDate: "2026-07-28",
    dueAt: "2026-07-28T19:00",
    priority: "낮음",
    needsReport: true,
    needsPhoto: true,
    location: "충남 보령 대천동 그랜드상가",
    status: "확인함",
    acknowledgedAt: "2026-07-28T07:45",
    ackResponse: "확인했습니다",
    progress: 0,
    lastUpdateAt: "2026-07-28T07:45",
  },
  {
    id: "t10",
    title: "홍성 준공서류 누락분 검토",
    projectId: "p3",
    content: "준공사진 4장과 세금계산서, 잔금 청구서 항목을 다시 확인해 주세요.",
    assignerId: "u2",
    assigneeId: "u3",
    watcherIds: [],
    createdAt: "2026-07-28T09:30",
    startDate: "2026-07-28",
    dueAt: "2026-07-30T18:00",
    priority: "보통",
    needsReport: false,
    needsPhoto: false,
    location: "사무실",
    status: "지시됨",
    progress: 0,
    lastUpdateAt: "2026-07-28T09:30",
  },
  {
    id: "t11",
    title: "대천동 4층 자재 반입 확인",
    projectId: "p1",
    content: "4층에 반입된 UTP 케이블과 몰드 수량을 확인해 주세요.",
    assignerId: "u4",
    assigneeId: "u6",
    watcherIds: ["u2"],
    createdAt: "2026-07-28T08:00",
    startDate: "2026-07-28",
    dueAt: "2026-07-28T14:00",
    priority: "낮음",
    needsReport: true,
    needsPhoto: true,
    location: "충남 보령 대천동 그랜드상가",
    status: "완료보고",
    acknowledgedAt: "2026-07-28T08:05",
    ackResponse: "확인했습니다",
    progress: 100,
    lastUpdateAt: "2026-07-28T10:05",
  },
  {
    id: "t12",
    title: "군산 추가공사 서면승인 요청 발송",
    projectId: "p4",
    content: "CCTV 4대 추가와 위치 변경에 대한 추가견적서를 만들어 발주처에 보내 주세요.",
    assignerId: "u2",
    assigneeId: "u3",
    watcherIds: ["u2"],
    createdAt: "2026-07-28T09:50",
    startDate: "2026-07-28",
    dueAt: "2026-07-29T12:00",
    priority: "긴급",
    needsReport: false,
    needsPhoto: false,
    location: "사무실",
    status: "확인함",
    acknowledgedAt: "2026-07-28T09:55",
    ackResponse: "확인했습니다",
    progress: 20,
    lastUpdateAt: "2026-07-28T09:55",
  },
];

export const SCHEDULES: ScheduleItem[] = [
  {
    id: "s1",
    title: "서천 장항산단 통신상태 점검",
    projectId: "p2",
    region: "충남 서천",
    assigneeId: "u4",
    date: "2026-07-28",
    start: "10:00",
    end: "11:00",
    travelMinutes: 0,
    status: "예정",
    taskId: "t1",
    note: "케이블 입고 전 배선 경로 확인",
  },
  {
    id: "s2",
    title: "보령 공공시설 준공사진 촬영",
    projectId: "p6",
    region: "충남 보령",
    assigneeId: "u4",
    date: "2026-07-28",
    start: "11:30",
    end: "13:00",
    travelMinutes: 55,
    status: "예정",
    taskId: "t3",
    note: "장비실·민원실 4장",
  },
  {
    id: "s3",
    title: "군산 CCTV 위치 재확인",
    projectId: "p4",
    region: "전북 군산",
    assigneeId: "u5",
    date: "2026-07-28",
    start: "09:00",
    end: "12:00",
    travelMinutes: 0,
    status: "진행 중",
    acknowledgedAt: "2026-07-28T07:10",
    taskId: "t2",
  },
  {
    id: "s4",
    title: "홍성 네트워크 속도 측정",
    projectId: "p3",
    region: "충남 홍성",
    assigneeId: "u5",
    date: "2026-07-28",
    start: "15:00",
    end: "16:30",
    travelMinutes: 95,
    status: "예정",
    acknowledgedAt: "2026-07-28T08:20",
    taskId: "t4",
  },
  {
    id: "s5",
    title: "서천 자재 입고 입회",
    projectId: "p2",
    region: "충남 서천",
    assigneeId: "u6",
    date: "2026-07-28",
    start: "09:30",
    end: "10:30",
    travelMinutes: 0,
    status: "진행 중",
    acknowledgedAt: "2026-07-28T08:45",
    taskId: "t5",
  },
  {
    id: "s6",
    title: "익산 물류창고 사양 협의",
    projectId: "p5",
    region: "전북 익산",
    assigneeId: "u6",
    date: "2026-07-28",
    start: "13:30",
    end: "15:00",
    travelMinutes: 80,
    status: "예정",
    taskId: "t8",
  },
  {
    id: "s7",
    title: "보령시청 준공검수 협의",
    projectId: "p6",
    region: "충남 보령",
    assigneeId: "u3",
    date: "2026-07-28",
    start: "14:00",
    end: "15:00",
    travelMinutes: 20,
    status: "예정",
    acknowledgedAt: "2026-07-28T09:05",
    taskId: "t6",
  },
  {
    id: "s8",
    title: "대천동 4층 자재 반입 확인",
    projectId: "p1",
    region: "충남 보령",
    assigneeId: "u6",
    date: "2026-07-29",
    start: "09:00",
    end: "10:00",
    travelMinutes: 0,
    status: "예정",
  },
  {
    id: "s9",
    title: "군산 추가공사 발주처 협의",
    projectId: "p4",
    region: "전북 군산",
    assigneeId: "u2",
    date: "2026-07-29",
    start: "14:00",
    end: "15:30",
    travelMinutes: 0,
    status: "예정",
  },
  {
    id: "s10",
    title: "익산 착공 전 현장 점검",
    projectId: "p5",
    region: "전북 익산",
    assigneeId: "u4",
    date: "2026-07-30",
    start: "10:00",
    end: "12:00",
    travelMinutes: 0,
    status: "예정",
  },
];

export const WORK_REPORTS: WorkReport[] = [
  {
    id: "r1",
    taskId: "t11",
    projectId: "p1",
    authorId: "u6",
    kind: "완료 보고",
    createdAt: "2026-07-28T10:05",
    raw: "4층 자재 반입 확인 끝. UTP 2박스, 몰드 40m 들어옴. 몰드가 10m 정도 모자랄 것 같음.",
    progress: 100,
    photoCount: 3,
    issue: "몰드 10m 부족 예상",
    next: "4층 배선 착수",
    eta: "내일 오전",
    summary: {
      done: "4층 자재 반입 확인 (UTP Cat.6 2박스, 몰드 40m)",
      materials: "몰드 약 10m 추가 필요",
      next: "4층 배선 착수",
      schedule: "내일 오전",
      needsManager: "자재 추가 발주 확인",
    },
    reviewStatus: "검토 대기",
  },
  {
    id: "r2",
    taskId: "t2",
    projectId: "p4",
    authorId: "u5",
    kind: "진행 보고",
    createdAt: "2026-07-27T13:40",
    raw: "외곽 배관 매설 끝냈고 CCTV 위치 2개는 발주처가 바꾸겠다고 함. 4대 더 달아야 할 것 같음.",
    progress: 60,
    photoCount: 10,
    issue: "발주처 요청으로 위치 변경, 수량 추가",
    next: "변경 위치 재시공",
    summary: {
      done: "외곽 CCTV 배관 매설 구간 완료",
      changes: "설치 위치 2개소 변경 요청",
      materials: "CCTV 4대 추가 필요",
      next: "변경 위치 재시공",
      needsManager: "추가공사 서면승인 필요",
    },
    reviewStatus: "승인",
    reviewNote: "추가견적 발송 후 진행하세요.",
    reviewedAt: "2026-07-27T15:10",
    reviewerId: "u2",
  },
  {
    id: "r3",
    taskId: "t4",
    projectId: "p3",
    authorId: "u5",
    kind: "시작 보고",
    createdAt: "2026-07-28T09:10",
    raw: "홍성 현장 도착. 3층부터 속도 측정 시작합니다.",
    progress: 40,
    photoCount: 1,
    next: "4~5층 측정",
    reviewStatus: "승인",
    reviewedAt: "2026-07-28T09:25",
    reviewerId: "u4",
  },
  {
    id: "r4",
    projectId: "p1",
    authorId: "u4",
    kind: "일일 업무보고",
    createdAt: "2026-07-27T18:20",
    raw: "대천동 3층 배선 4명 투입해서 8시간 작업. 천장 마감 일정 바뀌어서 4층은 2일 밀릴 수 있음.",
    progress: 72,
    photoCount: 6,
    issue: "천장 마감 일정 변경",
    next: "3층 잔여 배선 마무리",
    reviewStatus: "승인",
    reviewedAt: "2026-07-27T19:00",
    reviewerId: "u2",
  },
];

export const TIMELINE: TimelineEvent[] = [
  {
    id: "e1",
    projectId: "p4",
    kind: "업무지시",
    actorId: "u2",
    at: "2026-07-26T09:00",
    text: "군산 CCTV 위치 변경 확인 업무를 이민수 현장기사에게 전달했습니다.",
    taskId: "t2",
  },
  {
    id: "e2",
    projectId: "p4",
    kind: "직원 확인",
    actorId: "u5",
    at: "2026-07-26T09:20",
    text: "이민수 현장기사가 업무를 확인했습니다.",
    taskId: "t2",
  },
  {
    id: "e3",
    projectId: "p4",
    kind: "사진",
    actorId: "u5",
    at: "2026-07-27T13:35",
    text: "외곽 배관 매설 구간 사진을 올렸습니다.",
    photoCount: 10,
    taskId: "t2",
  },
  {
    id: "e4",
    projectId: "p4",
    kind: "진행보고",
    actorId: "u5",
    at: "2026-07-27T13:40",
    text: "배관 매설 완료. 발주처가 CCTV 위치 2개소 변경과 4대 추가를 요청했습니다.",
    taskId: "t2",
  },
  {
    id: "e5",
    projectId: "p4",
    kind: "관리자 댓글",
    actorId: "u2",
    at: "2026-07-27T15:10",
    text: "추가견적 발송 후 진행하세요. 서면승인 전에는 시공하지 마세요.",
    taskId: "t2",
  },
  {
    id: "e6",
    projectId: "p4",
    kind: "업무지시",
    actorId: "u2",
    at: "2026-07-28T09:50",
    text: "군산 추가공사 서면승인 요청 발송 업무를 김하늘 사무담당에게 전달했습니다.",
    taskId: "t12",
  },
  {
    id: "e7",
    projectId: "p2",
    kind: "업무지시",
    actorId: "u2",
    at: "2026-07-27T16:40",
    text: "서천 장항산단 현장 통신상태 점검 업무를 박정우 현장책임자에게 전달했습니다.",
    taskId: "t1",
  },
  {
    id: "e8",
    projectId: "p2",
    kind: "업무지시",
    actorId: "u2",
    at: "2026-07-28T08:30",
    text: "서천 자재 입고 확인 업무를 최영호 현장기사에게 전달했습니다.",
    taskId: "t5",
  },
  {
    id: "e9",
    projectId: "p1",
    kind: "완료보고",
    actorId: "u6",
    at: "2026-07-28T10:05",
    text: "4층 자재 반입 확인을 마치고 완료보고를 올렸습니다. 몰드 10m가 부족할 것 같습니다.",
    taskId: "t11",
  },
  {
    id: "e10",
    projectId: "p6",
    kind: "업무지시",
    actorId: "u2",
    at: "2026-07-27T09:00",
    text: "보령 공공시설 준공사진 제출 업무를 박정우 현장책임자에게 전달했습니다.",
    taskId: "t3",
  },
  {
    id: "e11",
    projectId: "p6",
    kind: "직원 확인",
    actorId: "u4",
    at: "2026-07-27T09:30",
    text: "박정우 현장책임자가 업무를 확인했습니다.",
    taskId: "t3",
  },
  {
    id: "e12",
    projectId: "p3",
    kind: "진행보고",
    actorId: "u5",
    at: "2026-07-28T09:10",
    text: "홍성 현장 도착 후 3층부터 네트워크 속도 측정을 시작했습니다.",
    taskId: "t4",
  },
];

/* ── 운영성과 (도입 전 기준값과 목표치) ───────────────── */

export interface PerfMetric {
  key: string;
  label: string;
  unit: string;
  before: number;
  target: number;
  /** 값이 낮을수록 좋은 지표인지 */
  lowerIsBetter: boolean;
  desc: string;
}

export const PERF_METRICS: PerfMetric[] = [
  {
    key: "ack",
    label: "업무 확인률",
    unit: "%",
    before: 64,
    target: 95,
    lowerIsBetter: false,
    desc: "지시한 업무를 담당자가 확인 버튼까지 누른 비율",
  },
  {
    key: "onTime",
    label: "기한 내 완료율",
    unit: "%",
    before: 71,
    target: 92,
    lowerIsBetter: false,
    desc: "완료기한 안에 완료보고까지 올라온 비율",
  },
  {
    key: "missed",
    label: "일정 누락",
    unit: "건/월",
    before: 7,
    target: 1,
    lowerIsBetter: true,
    desc: "확인되지 않아 놓친 현장 일정",
  },
  {
    key: "reportRate",
    label: "업무보고 제출률",
    unit: "%",
    before: 58,
    target: 90,
    lowerIsBetter: false,
    desc: "결과보고가 필요한 업무 중 실제 제출된 비율",
  },
  {
    key: "ackTime",
    label: "업무 확인 평균시간",
    unit: "시간",
    before: 6,
    target: 1,
    lowerIsBetter: true,
    desc: "지시 후 담당자가 확인하기까지 걸린 시간",
  },
  {
    key: "reviewTime",
    label: "완료 후 관리자 확인",
    unit: "일",
    before: 2.1,
    target: 0.5,
    lowerIsBetter: true,
    desc: "완료보고 후 관리자가 검토하기까지 걸린 시간",
  },
  {
    key: "digitized",
    label: "구두지시 시스템 등록률",
    unit: "%",
    before: 22,
    target: 80,
    lowerIsBetter: false,
    desc: "전화·카톡·구두로 전달된 업무가 시스템에 등록된 비율",
  },
  {
    key: "delayed",
    label: "프로젝트 지연 건수",
    unit: "건/월",
    before: 4,
    target: 1,
    lowerIsBetter: true,
    desc: "일정 미확인·자재 지연으로 공정이 밀린 건수",
  },
];

/* ── 조달 인사이트 (샘플 데이터) ───────────────────── */

export const PROCUREMENT_REGION = [
  { region: "충남 보령", count: 34, amount: 128000 },
  { region: "충남 서천", count: 21, amount: 76000 },
  { region: "충남 홍성", count: 27, amount: 94000 },
  { region: "충남 서산", count: 19, amount: 71000 },
  { region: "전북 군산", count: 31, amount: 115000 },
  { region: "전북 익산", count: 24, amount: 88000 },
];

export const PROCUREMENT_AGENCY = [
  { agency: "보령시청", last30: 7, prev30: 4, amount: 42000 },
  { agency: "서천군청", last30: 4, prev30: 4, amount: 21000 },
  { agency: "홍성군청", last30: 6, prev30: 3, amount: 33000 },
  { agency: "군산시청", last30: 5, prev30: 6, amount: 38000 },
  { agency: "충남교육청", last30: 9, prev30: 5, amount: 51000 },
  { agency: "한국농어촌공사 충남본부", last30: 3, prev30: 2, amount: 18000 },
];

export const PROCUREMENT_BRAND = [
  { brand: "A사 (CCTV)", share: 34, delta: -4 },
  { brand: "B사 (CCTV)", share: 27, delta: 6 },
  { brand: "C사 (네트워크)", share: 21, delta: 1 },
  { brand: "D사 (출입통제)", share: 11, delta: -2 },
  { brand: "기타", share: 7, delta: -1 },
];

export const PROCUREMENT_COMPETITORS = [
  {
    name: "○○전기통신 (대전)",
    note: "최근 30일 보령·서천 지역 3건 낙찰 — 신규 진입",
    level: "danger" as const,
  },
  {
    name: "△△시스템 (천안)",
    note: "충남교육청 CCTV 발주 2건 참여 — 관심 필요",
    level: "warning" as const,
  },
  {
    name: "□□ENG (군산)",
    note: "군산 지역 점유 유지, 변동 없음",
    level: "info" as const,
  },
];

export const PROCUREMENT_WATCH = [
  { agency: "충남교육청", reason: "최근 30일 발주 9건 (직전 5건) — 80% 증가" },
  { agency: "보령시청", reason: "하반기 통신설비 교체 예산 집행 시작" },
  { agency: "홍성군청", reason: "CCTV 통합관제 관련 발주 증가" },
];

/* ── 현장 설비 연동 준비 (데모) ────────────────────── */

export const FACILITIES = [
  { name: "보령 본사 CCTV", kind: "CCTV", status: "온라인", detail: "카메라 8대 · 저장 28일", tone: "success" as const },
  { name: "보령 자재창고 출입통제", kind: "출입통제", status: "정상", detail: "등록 인원 14명", tone: "success" as const },
  { name: "군산 산업단지 현장 CCTV", kind: "CCTV", status: "연동 대기", detail: "공사 완료 후 연동 예정", tone: "warning" as const },
  { name: "익산 물류창고 출입통제", kind: "출입통제", status: "연동 대기", detail: "장비 사양 협의 중", tone: "warning" as const },
];

export const ACCESS_LOGS = [
  { at: "2026-07-28 07:42", who: "박정우 현장책임자", place: "보령 자재창고", action: "출입" },
  { at: "2026-07-28 08:05", who: "최영호 현장기사", place: "보령 자재창고", action: "출입" },
  { at: "2026-07-27 18:20", who: "이민수 현장기사", place: "보령 본사", action: "퇴근" },
];
